[theme]
base="light"

# Primary accent color for interactive elements.
primaryColor = '#2e86de'

# Background color for the main content area.
backgroundColor= '#FFF'

# Background color used for the sidebar and most interactive widgets.
#secondaryBackgroundColor = '#dcdde1'

# Color used for almost all text.
textColor = '#222f3e'

# Font family for all text in the app, except code blocks. 
# One of "sans serif", "serif", or "monospace".
font = "sans serif"
